# Generated by Django 4.2.30 on 2026-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaborListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electrician", "Electrician"),
                            ("Plumber", "Plumber"),
                            ("Painter", "Painter"),
                            ("Carpenter", "Carpenter"),
                            ("Cleaner", "Cleaner"),
                            ("Mason", "Mason"),
                            ("Gardener", "Gardener"),
                            ("General Laborer", "General Laborer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("skills", models.TextField(blank=True, default="")),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Weekends", "Weekends"),
                            ("On Call", "On Call"),
                        ],
                        default="Full Time",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="labor_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Labor Listing",
                "verbose_name_plural": "Labor Listings",
                "ordering": ["-created_at"],
            },
        ),
    ]
